### ISSUE TITLE
Is it possible to Get command response or save response locally?

### ISSUE THREAD

**Issue by tamaker** [shaishab/node-command-line#5]
I'm using node-command-line in a node application that will need to 
1.) run the command
2.) get the response from the command to use as either a parse-able variable (string(s)) or save it with FS module to a local file

Is this possible?

I can see that it's successfully RUNNING the command, but I need to be able to USE the response from the command.

**Comment by shaishab** [comment]
> I'm using node-command-line in a node application that will need to 1.) run the command 2.) get the response from the command to use as either a parse-able variable (string(s)) or save it with FS module to a local file
> 
> Is this possible?
> 
> I can see that it's successfully RUNNING the command, but I need to be able to USE the response from the command.

@tamaker 
Yes, you can whatever you want after getting response from the library. Please see the README fiel
